// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type ConnectRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Genesis time unix format
	GenesisTime          int64    `protobuf:"varint,3,opt,name=genesisTime,proto3" json:"genesisTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConnectRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConnectRequest) GetGenesisTime() int64 {
	if m != nil {
		return m.GenesisTime
	}
	return 0
}

type ConnectResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConnectResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *ConnectResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChainHeadRequest struct {
	HeadSlot             uint64   `protobuf:"varint,1,opt,name=headSlot,proto3" json:"headSlot,omitempty"`
	HeadBlockRoot        string   `protobuf:"bytes,2,opt,name=headBlockRoot,proto3" json:"headBlockRoot,omitempty"`
	FinalizedSlot        uint64   `protobuf:"varint,3,opt,name=finalizedSlot,proto3" json:"finalizedSlot,omitempty"`
	FinalizedBlockRoot   string   `protobuf:"bytes,4,opt,name=finalizedBlockRoot,proto3" json:"finalizedBlockRoot,omitempty"`
	JustifiedSlot        uint64   `protobuf:"varint,5,opt,name=justifiedSlot,proto3" json:"justifiedSlot,omitempty"`
	JustifiedBlockRoot   string   `protobuf:"bytes,6,opt,name=justifiedBlockRoot,proto3" json:"justifiedBlockRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainHeadRequest) Reset()         { *m = ChainHeadRequest{} }
func (m *ChainHeadRequest) String() string { return proto.CompactTextString(m) }
func (*ChainHeadRequest) ProtoMessage()    {}
func (*ChainHeadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ChainHeadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainHeadRequest.Unmarshal(m, b)
}
func (m *ChainHeadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainHeadRequest.Marshal(b, m, deterministic)
}
func (m *ChainHeadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainHeadRequest.Merge(m, src)
}
func (m *ChainHeadRequest) XXX_Size() int {
	return xxx_messageInfo_ChainHeadRequest.Size(m)
}
func (m *ChainHeadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainHeadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainHeadRequest proto.InternalMessageInfo

func (m *ChainHeadRequest) GetHeadSlot() uint64 {
	if m != nil {
		return m.HeadSlot
	}
	return 0
}

func (m *ChainHeadRequest) GetHeadBlockRoot() string {
	if m != nil {
		return m.HeadBlockRoot
	}
	return ""
}

func (m *ChainHeadRequest) GetFinalizedSlot() uint64 {
	if m != nil {
		return m.FinalizedSlot
	}
	return 0
}

func (m *ChainHeadRequest) GetFinalizedBlockRoot() string {
	if m != nil {
		return m.FinalizedBlockRoot
	}
	return ""
}

func (m *ChainHeadRequest) GetJustifiedSlot() uint64 {
	if m != nil {
		return m.JustifiedSlot
	}
	return 0
}

func (m *ChainHeadRequest) GetJustifiedBlockRoot() string {
	if m != nil {
		return m.JustifiedBlockRoot
	}
	return ""
}

type ChainHeadResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainHeadResponse) Reset()         { *m = ChainHeadResponse{} }
func (m *ChainHeadResponse) String() string { return proto.CompactTextString(m) }
func (*ChainHeadResponse) ProtoMessage()    {}
func (*ChainHeadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ChainHeadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainHeadResponse.Unmarshal(m, b)
}
func (m *ChainHeadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainHeadResponse.Marshal(b, m, deterministic)
}
func (m *ChainHeadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainHeadResponse.Merge(m, src)
}
func (m *ChainHeadResponse) XXX_Size() int {
	return xxx_messageInfo_ChainHeadResponse.Size(m)
}
func (m *ChainHeadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainHeadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainHeadResponse proto.InternalMessageInfo

func (m *ChainHeadResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *ChainHeadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HeartbeatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

type HeartbeatResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *HeartbeatResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TelemetryRequest struct {
	Peers                int64    `protobuf:"varint,1,opt,name=peers,proto3" json:"peers,omitempty"`
	Syncing              bool     `protobuf:"varint,2,opt,name=syncing,proto3" json:"syncing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryRequest) Reset()         { *m = TelemetryRequest{} }
func (m *TelemetryRequest) String() string { return proto.CompactTextString(m) }
func (*TelemetryRequest) ProtoMessage()    {}
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *TelemetryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryRequest.Unmarshal(m, b)
}
func (m *TelemetryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryRequest.Marshal(b, m, deterministic)
}
func (m *TelemetryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryRequest.Merge(m, src)
}
func (m *TelemetryRequest) XXX_Size() int {
	return xxx_messageInfo_TelemetryRequest.Size(m)
}
func (m *TelemetryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryRequest proto.InternalMessageInfo

func (m *TelemetryRequest) GetPeers() int64 {
	if m != nil {
		return m.Peers
	}
	return 0
}

func (m *TelemetryRequest) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

type TelemetryResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryResponse) Reset()         { *m = TelemetryResponse{} }
func (m *TelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*TelemetryResponse) ProtoMessage()    {}
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *TelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryResponse.Unmarshal(m, b)
}
func (m *TelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryResponse.Marshal(b, m, deterministic)
}
func (m *TelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryResponse.Merge(m, src)
}
func (m *TelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_TelemetryResponse.Size(m)
}
func (m *TelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryResponse proto.InternalMessageInfo

func (m *TelemetryResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *TelemetryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*ConnectRequest)(nil), "proto.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "proto.ConnectResponse")
	proto.RegisterType((*ChainHeadRequest)(nil), "proto.ChainHeadRequest")
	proto.RegisterType((*ChainHeadResponse)(nil), "proto.ChainHeadResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "proto.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "proto.HeartbeatResponse")
	proto.RegisterType((*TelemetryRequest)(nil), "proto.TelemetryRequest")
	proto.RegisterType((*TelemetryResponse)(nil), "proto.TelemetryResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0xb4, 0xc9, 0x96, 0x87, 0x36, 0xc2, 0xd3, 0x80, 0xa8, 0x5c, 0xaa, 0x08, 0xa4,
	0x89, 0x43, 0x0f, 0xe5, 0xc6, 0x09, 0x6d, 0x9a, 0x34, 0x89, 0xc3, 0x24, 0xaf, 0x1f, 0x00, 0xaf,
	0x7b, 0x6b, 0xcd, 0x5a, 0xbb, 0xc4, 0x2e, 0xd2, 0x38, 0xf1, 0x05, 0xf8, 0xce, 0xc8, 0x76, 0xe2,
	0x26, 0x0d, 0x07, 0x0e, 0x3b, 0x35, 0xef, 0xff, 0xac, 0xdf, 0xff, 0xf9, 0xff, 0x5c, 0xc8, 0xf8,
	0x56, 0x4c, 0xb7, 0x95, 0x32, 0x0a, 0x13, 0xf7, 0x53, 0x7e, 0x83, 0xd3, 0x4b, 0x25, 0x25, 0x2d,
	0x0c, 0xa3, 0x1f, 0x3b, 0xd2, 0x06, 0x11, 0x46, 0x92, 0x6f, 0xa8, 0x88, 0x26, 0xd1, 0x79, 0xc6,
	0xdc, 0x37, 0x16, 0x70, 0xf4, 0x93, 0x2a, 0x2d, 0x94, 0x2c, 0x62, 0x27, 0x37, 0x25, 0x4e, 0xe0,
	0xc5, 0x92, 0x24, 0x69, 0xa1, 0xe7, 0x62, 0x43, 0xc5, 0x70, 0x12, 0x9d, 0x0f, 0x59, 0x5b, 0x2a,
	0x57, 0xf0, 0x32, 0x38, 0xe8, 0xad, 0x92, 0x9a, 0xf0, 0x0c, 0x12, 0xa3, 0x1e, 0x49, 0xd6, 0x1e,
	0xbe, 0xc0, 0x0f, 0x90, 0x6a, 0xc3, 0xcd, 0x4e, 0x3b, 0x8f, 0xd3, 0xd9, 0x89, 0x9f, 0x74, 0x7a,
	0xeb, 0x44, 0x56, 0x37, 0xed, 0x2c, 0x1b, 0xd2, 0x9a, 0x2f, 0xbd, 0x5b, 0xc6, 0x9a, 0xb2, 0xfc,
	0x1d, 0x43, 0x7e, 0xb9, 0xe2, 0x42, 0x5e, 0x13, 0xbf, 0x6f, 0xae, 0x33, 0x86, 0xe3, 0x15, 0xf1,
	0xfb, 0xdb, 0xb5, 0x32, 0xce, 0x6e, 0xc4, 0x42, 0x8d, 0xef, 0xe1, 0xc4, 0x7e, 0x5f, 0xac, 0xd5,
	0xe2, 0x91, 0x29, 0x65, 0xea, 0xcb, 0x75, 0x45, 0x7b, 0xea, 0x41, 0x48, 0xbe, 0x16, 0xbf, 0xc8,
	0x63, 0x86, 0x0e, 0xd3, 0x15, 0x71, 0x0a, 0x18, 0x84, 0x3d, 0x70, 0xe4, 0x80, 0xff, 0xe8, 0x58,
	0xea, 0xf7, 0x9d, 0x36, 0xe2, 0x41, 0xd4, 0xd4, 0xc4, 0x53, 0x3b, 0xa2, 0xa5, 0x06, 0x61, 0x4f,
	0x4d, 0x3d, 0xb5, 0xdf, 0x29, 0xe7, 0xf0, 0xaa, 0x95, 0x40, 0x1d, 0xf7, 0x3e, 0xd8, 0xe8, 0x3f,
	0x83, 0x8d, 0xbb, 0xc1, 0x22, 0xe4, 0xd7, 0xc4, 0x2b, 0x73, 0x47, 0xbc, 0x79, 0x26, 0xd6, 0xa9,
	0xa5, 0x3d, 0x97, 0xd3, 0x05, 0xe4, 0x73, 0x5a, 0xd3, 0x86, 0x4c, 0xf5, 0xd4, 0x6c, 0xf0, 0x0c,
	0x92, 0x2d, 0x51, 0xe5, 0x99, 0x43, 0xe6, 0x0b, 0xcb, 0xd0, 0x4f, 0x72, 0x21, 0xe4, 0xd2, 0x31,
	0x8e, 0x59, 0x53, 0xda, 0xc9, 0x5a, 0x8c, 0x67, 0x9a, 0xec, 0xe3, 0x3b, 0x48, 0xfd, 0x59, 0x4c,
	0x21, 0xbe, 0xf9, 0x9a, 0x0f, 0x30, 0x83, 0xe4, 0x8a, 0xb1, 0x1b, 0x96, 0x47, 0xb3, 0x3f, 0x31,
	0x64, 0x57, 0x66, 0x35, 0xb3, 0x14, 0x8d, 0x9f, 0xe1, 0xa8, 0x7e, 0xf1, 0xf8, 0xba, 0xb6, 0xe9,
	0xfe, 0xc7, 0xc6, 0x6f, 0x0e, 0x65, 0x3f, 0x65, 0x39, 0xc0, 0x2f, 0x90, 0x85, 0x05, 0xe2, 0xdb,
	0xe6, 0xd8, 0xc1, 0xa3, 0x1e, 0x17, 0xfd, 0x46, 0x9b, 0x10, 0x16, 0x13, 0x08, 0x87, 0xeb, 0x0b,
	0x84, 0xde, 0x0e, 0x3d, 0x21, 0x04, 0x18, 0x08, 0x87, 0x6b, 0x09, 0x84, 0x5e, 0xd6, 0xe5, 0xe0,
	0x2e, 0x75, 0xad, 0x4f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xbc, 0x06, 0x24, 0x70, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Eth2StatsClient is the client API for Eth2Stats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Eth2StatsClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	ChainHead(ctx context.Context, in *ChainHeadRequest, opts ...grpc.CallOption) (*ChainHeadResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Telemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
}

type eth2StatsClient struct {
	cc *grpc.ClientConn
}

func NewEth2StatsClient(cc *grpc.ClientConn) Eth2StatsClient {
	return &eth2StatsClient{cc}
}

func (c *eth2StatsClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/proto.Eth2stats/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eth2StatsClient) ChainHead(ctx context.Context, in *ChainHeadRequest, opts ...grpc.CallOption) (*ChainHeadResponse, error) {
	out := new(ChainHeadResponse)
	err := c.cc.Invoke(ctx, "/proto.Eth2stats/ChainHead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eth2StatsClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/proto.Eth2stats/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eth2StatsClient) Telemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, "/proto.Eth2stats/Telemetry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Eth2StatsServer is the server API for Eth2Stats service.
type Eth2StatsServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	ChainHead(context.Context, *ChainHeadRequest) (*ChainHeadResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Telemetry(context.Context, *TelemetryRequest) (*TelemetryResponse, error)
}

func RegisterEth2StatsServer(s *grpc.Server, srv Eth2StatsServer) {
	s.RegisterService(&_Eth2Stats_serviceDesc, srv)
}

func _Eth2Stats_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Eth2StatsServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Eth2stats/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Eth2StatsServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eth2Stats_ChainHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Eth2StatsServer).ChainHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Eth2stats/ChainHead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Eth2StatsServer).ChainHead(ctx, req.(*ChainHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eth2Stats_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Eth2StatsServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Eth2stats/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Eth2StatsServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eth2Stats_Telemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Eth2StatsServer).Telemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Eth2stats/Telemetry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Eth2StatsServer).Telemetry(ctx, req.(*TelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eth2Stats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Eth2stats",
	HandlerType: (*Eth2StatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Eth2Stats_Connect_Handler,
		},
		{
			MethodName: "ChainHead",
			Handler:    _Eth2Stats_ChainHead_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Eth2Stats_Heartbeat_Handler,
		},
		{
			MethodName: "Telemetry",
			Handler:    _Eth2Stats_Telemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
